name: Python Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.10
      
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                    
      - name: Test With `pytest`
        run: |
          pytest
